name: ferc-xbrl-extractor
channels:
  - conda-forge
  - defaults
dependencies:
  # Packages required for setting up the environment
  - pip>=21.0,<23
  - python>=3.10,<3.12
  - setuptools<66

  # XBRL parsing library
  - pip:
      - --editable ./[docs,tests,dev]
